MCBAWebApp/Controllers/BillPayController.cs
using MCBADataLibrary.Data;
using MCBADataLibrary.Enums;
using MCBADataLibrary.Models;
using MCBAWebApp.Filters;
using MCBAWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace MCBAWebApp.Controllers;

[AuthorizeCustomer]
public class BillPayController : Controller
{
    private readonly BankDbContext _context;
    private int CustomerID => HttpContext.Session.GetInt32(nameof(Customer.CustomerID))!.Value;

    public BillPayController(BankDbContext context)
    {
        _context = context;
    }

    public async Task<IActionResult> Index()
    {
        var bills = await _context.BillPayments
            .Where(b => b.Account.CustomerID == CustomerID)
            .Include(b => b.Payee)
            .OrderBy(b => b.ScheduleTimeUtc)
            .ToListAsync();

        return View(bills);
    }

    public async Task<IActionResult> CancelBill(int id)
    {
        var bill = await _context.BillPayments.FindAsync(id);
        _context.BillPayments.Remove(bill!);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> NewBill()
    {
        var customerAccounts = await _context.Accounts
            .Where(a => a.CustomerID == CustomerID)
            .ToListAsync();
        var payees = await _context.Payees.ToListAsync();

        return View(new BillViewModel
        {
            Accounts = customerAccounts.Select(a => new SelectListItem
            {
                Value = a.AccountNumber.ToString(),
                Text = $"{a.AccountNumber}: {a.AccountType}, Available Balance: {a.Balance - a.MinimumBalance, 0:C2}"
            }),
            Payees = payees.Select(p => new SelectListItem
            {
                Value = p.PayeeID.ToString(),
                Text = p.Name
            })
        });
    }

    [HttpPost]
    public async Task<IActionResult> NewBill(BillViewModel viewModel)
    {
        viewModel.Accounts = _context.Accounts
                .Where(a => a.CustomerID == CustomerID)
                .Select(a => new SelectListItem
                {
                    Value = a.AccountNumber.ToString(),
                    Text = $"{a.AccountNumber}: {a.AccountType}, Available Balance: {a.Balance - a.MinimumBalance, 0:C2}"
                });
        viewModel.Payees = _context.Payees.Select(p => new SelectListItem
        {
            Value = p.PayeeID.ToString(),
            Text = p.Name
        });

        if (!ModelState.IsValid)
        {
            return View(viewModel);
        }

        await _context.BillPayments.AddAsync(new BillPay
        {
            AccountNumber = viewModel.SelectedAccount,
            PayeeID = viewModel.SelectedPayee,
            Amount = viewModel.Amount,
            ScheduleTimeUtc = viewModel.ScheduleTime.ToUniversalTime(),
            Period = viewModel.Period
        });

        await _context.SaveChangesAsync();

        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> RetryBill(int id)
    {
        var bill = await _context.BillPayments
            .Include(b => b.Account)
            .FirstAsync(b => b.BillPayID == id);
        bill.Account.ProcessBill(bill);

        if (bill.BillStatus == BillStatus.Complete)
        {
            _context.BillPayments.Remove(bill);
        }

        await _context.SaveChangesAsync();

        return RedirectToAction(nameof(Index));
    }
}

MCBAWebApp/Controllers/LoginController.cs
using MCBADataLibrary.Data;
using MCBADataLibrary.Enums;
using MCBADataLibrary.Models;
using MCBAWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SimpleHashing.Net;

namespace MCBAWebApp.Controllers;

public class LoginController : Controller
{
    private readonly BankDbContext _context;
    private static readonly SimpleHash simpleHash = new();

    public LoginController(BankDbContext context) => _context = context;

    public IActionResult Login() => View();

    [HttpPost]
    public async Task<IActionResult> Login(LoginViewModel loginViewData)
    {
        var login = await _context.Logins
            .Include(l => l.Customer)
            .ThenInclude(c => c.Image)
            .FirstOrDefaultAsync(l => l.LoginID == loginViewData.LoginID);

        if (!ModelState.IsValid)
        {
            return View();
        }

        if (login is null || !simpleHash.Verify(loginViewData.Password, login.PasswordHash))
        {
            ModelState.AddModelError("LoginFailure", "Login ID and/or password were incorrect.");
            return View();
        }

        if (login.Customer.CustomerStatus == CustomerStatus.Blocked)
        {
            ModelState.AddModelError("LoginFailure", "Your account has been blocked, please contact MCBA administrators.");
            return View();
        }

        HttpContext.Session.SetInt32(nameof(Customer.CustomerID), login.CustomerID);
        HttpContext.Session.SetString(nameof(Customer.Name), login.Customer.Name);

        if (login.Customer.Image is not null && login.Customer.Image.Image is not null)
        {
            HttpContext.Session.SetString(nameof(Customer.Image), login.Customer.Image.Image);
        }

        return RedirectToAction("Index", "Customer");
    }

    public IActionResult Logout()
    {
        HttpContext.Session.Clear();
        return RedirectToAction("Index", "Home");
    }
}

MCBAWebApp/Controllers/ProfileController.cs
using ImageMagick;
using MCBADataLibrary.Data;
using MCBADataLibrary.Models;
using MCBAWebApp.Filters;
using MCBAWebApp.Models;
using MCBAWebApp.Utilities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SimpleHashing.Net;

namespace MCBAWebApp.Controllers;

[AuthorizeCustomer]
public class ProfileController : Controller
{
    private readonly BankDbContext _context;
    private static readonly SimpleHash simpleHash = new();

    public ProfileController(BankDbContext context) => _context = context;

    private int CustomerID => HttpContext.Session.GetInt32(nameof(Customer.CustomerID))!.Value;

    public async Task<IActionResult> Index()
    {
        var customer = await _context.Customers.FindAsync(CustomerID);
        return View(customer);
    }

    public async Task<IActionResult> EditProfile()
    {
        var customer = await _context.Customers.FindAsync(CustomerID);
        return View(new ProfileViewModel()
        {
            Name = customer!.Name,
            TFN = customer.TFN,
            Address = customer.Address,
            City = customer.City,
            State = customer.State,
            PostCode = customer.PostCode,
            Mobile = customer.Mobile
        });

    }

    public async Task<IActionResult> ChangeImage()
    {
        var customerImage = await _context.CustomerImages.FirstOrDefaultAsync(i => i.CustomerID == CustomerID);
        return View(new ImageViewModel
        {
            CurrentImage = customerImage
        });
    }

    [HttpPost]
    public async Task<IActionResult> ChangeImage(ImageViewModel viewModel)
    {
        if (!ModelState.IsValid)
        {
            return View(viewModel);
        }

        string? image = null;
        if (viewModel.Image is not null)
        {
            var maxSize = new MagickGeometry(400, 400)
            {
                IgnoreAspectRatio = false,
                FillArea = false,
            };

            using var magickImage = new MagickImage(await viewModel.Image.GetBytes());
            magickImage.Format = MagickFormat.Jpg;
            magickImage.Resize(maxSize);
            image = magickImage.ToBase64();
        }

        var customerImage = await _context.CustomerImages
            .FirstOrDefaultAsync(i => i.CustomerID == CustomerID);

        if (customerImage is null)
        {
            _context.CustomerImages.Add(new CustomerImage
            {
                CustomerID = CustomerID,
                Image = image
            });
        }
        else
        {
            customerImage.Image = image;
        }

        if (image is not null)
        {
            HttpContext.Session.SetString(nameof(Customer.Image), image!);
        }

        await _context.SaveChangesAsync();

        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> DeleteImage()
    {
        var customerImage = await _context.CustomerImages.FirstOrDefaultAsync(i => i.CustomerID == CustomerID);
        if (customerImage is not null)
        {
            _context.CustomerImages.Remove(customerImage);
            await _context.SaveChangesAsync();
            HttpContext.Session.Remove(nameof(Customer.Image));
        }
        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    public async Task<IActionResult> EditProfile(ProfileViewModel profile)
    {

        if (!ModelState.IsValid)
        {
            return View(profile);
        }

        var customer = await _context.Customers
            .FirstAsync(c => c.CustomerID == CustomerID);
        customer!.Name = profile.Name;
        customer.Address = profile.Address;
        customer.City = profile.City;
        customer.State = profile.State;
        customer.PostCode = profile.PostCode;
        customer.Mobile = profile.Mobile;
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    public IActionResult ChangePassword()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> ChangePassword(PasswordViewModel viewModel)
    {
        if (!ModelState.IsValid)
        {
            return View(viewModel);
        }

        bool validSubmission = true;

        var login = await _context.Logins.FirstAsync(l => l.CustomerID == CustomerID);

        if (!simpleHash.Verify(viewModel.OldPassword, login.PasswordHash))
        {
            ModelState.AddModelError(nameof(PasswordViewModel.OldPassword), "Password is incorrect.");
            validSubmission = false;
        }

        if (viewModel.NewPassword != viewModel.NewPasswordRepeat)
        {
            ModelState.AddModelError(nameof(PasswordViewModel.NewPassword), "Passwords do not match.");
            ModelState.AddModelError(nameof(PasswordViewModel.NewPasswordRepeat), "Passwords do not match.");
            validSubmission = false;
        }

        if (!validSubmission)
        {
            return View(viewModel);
        }

        login.PasswordHash = simpleHash.Compute(viewModel.NewPassword);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }
}

MCBAWebApp/Controllers/StatementsController.cs
using MCBADataLibrary.Data;
using MCBADataLibrary.Models;
using MCBAWebApp.Filters;
using MCBAWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using X.PagedList;

namespace MCBAWebApp.Controllers;

[AuthorizeCustomer]
public class StatementsController : Controller
{
    private readonly BankDbContext _context;

    public StatementsController(BankDbContext context) => _context = context;

    private int CustomerID => HttpContext.Session.GetInt32(nameof(Customer.CustomerID))!.Value;

    public async Task<IActionResult> Index()
    {
        var customer = await _context.Customers
            .Include(x => x.Accounts)
            .FirstAsync(c => c.CustomerID == CustomerID);

        return View(customer);
    }

    public async Task<IActionResult> Statement(int id, int? page)
    {
        var account = await _context.Accounts
            .Include(a => a.Transactions)
            .FirstAsync(a => a.AccountNumber == id);

        int pageSize = 4;
        int pageNumber = page ?? 1;

        return View(new StatementsViewModel() 
        { 
            Account = account, 
            Transactions = account.Transactions
                .OrderByDescending(t => t.TransactionTimeUtc)
                .ToPagedList(pageNumber, pageSize) 
        });
    }
}

MCBAWebApp/Views/Shared/_Layout.cshtml
@using MCBADataLibrary.Models;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MCBA</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MCBAWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Most Common Bank of Australia</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="d-sm-inline-flex justify-content-between ">

                    @{
                        var isLoggedIn = Context.Session.GetInt32(nameof(Customer.CustomerID)).HasValue;
                        var hasImage = Context.Session.GetInt32(nameof(Customer.Image)).HasValue;
                    }

                    <ul class="navbar-nav d-lg-flex align-items-center ml-auto">

                        @if (isLoggedIn)
                        {
                            <li class="nav-item">
                                <span class="nav-link text-dark">
                                    Welcome, @Context.Session.GetString(nameof(Customer.Name))
                                </span>
                            </li>
                        }

                        <li class="nav-item mx-1">
                            <a class="nav-link text-dark btn btn-outline-secondary" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        @if (isLoggedIn)
                        {
                            <li class="nav-item mx-1">
                                <a class="nav-link text-dark btn btn-outline-secondary" asp-area="" asp-controller="Customer" asp-action="Index">ATM</a>
                            </li>
                            <li class="nav-item mx-1">
                                <a class="nav-link text-dark btn btn-outline-secondary" asp-area="" asp-controller="BillPay" asp-action="Index">My Bills</a>
                            </li>
                            <li class="nav-item mx-1">
                                <a class="nav-link text-dark btn btn-outline-secondary" asp-area="" asp-controller="Statements" asp-action="Index">My Statements</a>
                            </li>
                            <li class="nav-item mx-1">
                                <a class="nav-link text-dark btn btn-outline-secondary" asp-area="" asp-controller="Profile" asp-action="Index">My Profile</a>
                            </li>
                            <li class="nav-item mx-1">
                                <a class="nav-link text-dark btn btn-outline-secondary" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                            </li>
                            @if (hasImage)
                            {
                                <li class="nav-item mx-1">
                                    <img src="data:image;base64, @Context.Session.GetString(nameof(Customer.Image))" alt="" class="rounded profile-image" />
                                </li>
                            }
                            else
                            {
                                <li class="nav-item mx-1">
                                    <img src="@Url.Content("~/DefaultPerson.png")" width="65" alt="" class="rounded" />
                                </li>
                            }
                        }
                        else
                        {
                            <li class="nav-item mx-1">
                                <a class="nav-link text-dark btn btn-outline-secondary" asp-area="" asp-controller="Login" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MCBA - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>